  
// Configuration: Add/remove repos here easily
const repositories = [
  {
    url: "https://github.com/atsuperman/play2/raw/main/",
    songs: [
{ file: "Balle Lakka.mp3", details: "🎬 Mankatha (2011) / 🎙️ Karthik, Vijay Yesudas, Anusha Dhayanidhi / 🎼 Yuvan Shankar Raja / 📝 Vaali" },
{ file: "January Madham.mp3", details: "🎬 7G Rainbow Colony (2004) / 🎙️ Mathangi Jagdish, Kunal Ganjawala / 🎼 Yuvan Shankar Raja / 📝 Na. Muthukumar" },
{ file: "Machi Open The Bottle.mp3", details: "🎬 Mankatha (2011) / 🎙️ Mano, Haricharan, Tippu, Naveen Madhav / 🎼 Yuvan Shankar Raja / 📝 Vaali" },
{ file: "Mangatha Extended Dance.mp3", details: "🎬 Mankatha (2011) / 🎙️ Yuvan Shankar Raja, Ranjith, Premgi Amaren, Sucharita, Anitha / 🎼 Yuvan Shankar Raja / 📝 Gangai Amaren, Sucharita, Yuvan Shankar Raja" },
{ file: "Vaada Bin Laada.mp3", details: "🎬 Mankatha (2011) / 🎙️ Krish, Suchitra / 🎼 Yuvan Shankar Raja / 📝 Vaali" },
{ file: "Vilayadu Mangatha.mp3", details: "🎬 Mankatha (2011) / 🎙️ Yuvan Shankar Raja, Ranjith, Premgi Amaren, Sucharita, Anitha / 🎼 Yuvan Shankar Raja / 📝 Gangai Amaren, Sucharita, Yuvan Shankar Raja" },
{ file: "Asku Maaro.mp3", details: "💽 Independent Single (2021) / 🎙️ Dharan Kumar, Sivaangi Krishnakumar / 🎼 Dharan Kumar / 📝 Dharan Kumar" },
{ file: "Bae.mp3", details: "🎬 Don (2022) / 🎙️ Adithya RK / 🎼 Anirudh Ravichander / 📝 Vignesh Shivan" },
{ file: "Jalabulajangu.mp3", details: "🎬 Don (2022) / 🎙️ Anirudh Ravichander / 🎼 Anirudh Ravichander / 📝 Rokesh" },
{ file: "Private Party.mp3", details: "🎬 Don (2022) / 🎙️ Anirudh Ravichander, Jonita Gandhi / 🎼 Anirudh Ravichander / 📝 Sivakarthikeyan" },
{ file: "Anaarkali.mp3", details: "🎬 Varushamellam Vasantham (2002) / 🎙️ P. Unnikrishnan, Ganga Sitharasu / 🎼 Sirpy / 📝 Ra. Ravishankar" },
{ file: "Enge andha vennila.mp3", details: "🎬 Varushamellam Vasantham (2002) / 🎙️ Unni Menon / 🎼 Sirpy / 📝 Ra. Ravishankar" },
{ file: "Enge Antha Vennila Female.mp3", details: "🎬 Varushamellam Vasantham (2002) / 🎙️ Sujatha Mohan / 🎼 Sirpy / 📝 Ra. Ravishankar" },
{ file: "Muthal muthalai unai.mp3", details: "🎬 Varushamellam Vasantham (2002) / 🎙️ P. Unnikrishnan, Sujatha Mohan / 🎼 Sirpy / 📝 Ra. Ravishankar" },
{ file: "Naan ready Neenga.mp3", details: "🎬 Varushamellam Vasantham (2002) / 🎙️ Krishnaraj, K. S. Chithra / 🎼 Sirpy / 📝 Manavai Ponmanikkam" },
{ file: "Erukanchedi ooram.mp3", details: "🎬 Santhaikku Vantha Kili (1995) / 🎙️ S. Janaki / 🎼 Deva / 📝 Vaali" },
{ file: "oothikka mama.mp3", details: "🎬 Santhaikku Vantha Kili (1995) / 🎙️ S. Janaki / 🎼 Deva / 📝 Vaali" },
{ file: "Poththu Athai.mp3", details: "🎬 Kadhal Kirukkan (2003) / 🎙️ Manikka Vinayagam, Malathy / 🎼 Deva / 📝 Deva Kumar" },
{ file: "Poove Muthal Poove.mp3", details: "🎬 Kadhal Kirukkan (2003) / 🎙️ Harish Raghavendra / 🎼 Deva / 📝 Kabilan" },
{ file: "Poove Mudhal poove female.mp3", details: "🎬 Kadhal Kirukkan (2003) / 🎙️ Chinmayi Sripada / 🎼 Deva / 📝 Kabilan" },
{ file: "Aattama TherottamaMix.mp3", details: "🎬 Singakutty (2008) / 🎙️ Anuradha Sriram, DJ Ewan / 🎼 Prasanna Shekhar / 📝 Vaali" },
{ file: "Aalana Naal Mudhala.mp3", details: "🎬 Kaadhal Kavithai (1998) / 🎙️ Pushpavanam Kuppusamy, Sowmya Raoh / 🎼 Ilaiyaraaja / 📝 Agathiyan" },
{ file: "Thath Thom thakdheemi.mp3", details: "🎬 Kaadhal Kavithai (1998) / 🎙️ Ila Arun, Swarnalatha / 🎼 Ilaiyaraaja / 📝 Agathiyan" },
{ file: "Oru Naalil Dream Mix.mp3", details: "🎬 Pudhupettai (2006) / 🎙️ Yuvan Shankar Raja / 🎼 Yuvan Shankar Raja / 📝 Na. Muthukumar" },
{ file: "Oru Naalil.mp3", details: "🎬 Pudhupettai (2006) / 🎙️ Yuvan Shankar Raja / 🎼 Yuvan Shankar Raja / 📝 Na. Muthukumar" },
{ file: "Pulpesum Poo Pesum.mp3", details: "🎬 Pudhupettai (2006) / 🎙️ Vijay Yesudas, Tanvi Shah, Premji Amaran, Yuvan Shankar Raja / 🎼 Yuvan Shankar Raja / 📝 Na. Muthukumar" },
{ file: "Appan Panna Thappula.mp3", details: "🎬 Thirupaachi (2005) / 🎙️ Pushpavanam Kuppusamy, Anuradha Sriram / 🎼 Dhina / 📝 Perarasu" },
{ file: "Kannum Kannumthan.mp3", details: "🎬 Thirupaachi (2005) / 🎙️ Harish Raghavendra, Uma Ramanan, Premji Amaren / 🎼 Mani Sharma / 📝 Perarasu" },
{ file: "Kattu Kattu.mp3", details: "🎬 Thirupaachi (2005) / 🎙️ Manikka Vinayagam, Sumangali / 🎼 Devi Sri Prasad / 📝 Perarasu" },
{ file: "Kumbida Pona deivam.mp3", details: "🎬 Thirupaachi (2005) / 🎙️ Shankar Mahadevan, Malathy Lakshman / 🎼 Dhina / 📝 Perarasu" },
{ file: "Nee Entha Ooru.mp3", details: "🎬 Thirupaachi (2005) / 🎙️ Tippu / 🎼 Dhina / 📝 Perarasu" },
{ file: "Adho Varaa.mp3", details: "🎬 Sullan (2004) / 🎙️ Pushpavanam Kuppusamy, Harini / 🎼 Vidyasagar / 📝 Pa. Vijay" },
{ file: "Thottu Thottu.mp3", details: "🎬 Ethirum Puthirum (1999) / 🎙️ Swarnalatha, Pushpavanam Kuppusamy / 🎼 Vidyasagar / 📝 Vairamuthu" },
{ file: "Kaathu Pasapasanga.mp3", details: "🎬 Ethirum Puthirum (1999) / 🎙️ Pushpavanam Kuppusamy, Malaysia Vasudevan, Anuradha Sriram, Gopal Rao / 🎼 Vidyasagar / 📝 Vairamuthu" },
{ file: "Potteduthu vachuvidava.mp3", details: "🎬 Style (2002) / 🎙️ Pushpavanam Kuppusamy, Swarnalatha / 🎼 Bharani / 📝 Pa. Vijay" },
{ file: "Thom Thom.mp3", details: "🎬 Alli Thandha Vaanam (2001) / 🎙️ Hariharan, K. S. Chithra / 🎼 Vidyasagar" },
{ file: "Vadi Vadi Nattukkattai.mp3", details: "🎬 Alli Thandha Vaanam (2001) / 🎙️ Shankar Mahadevan, Sujatha Mohan / 🎼 Vidyasagar" },
{ file: "Bothai yeri pochu.mp3", details: "🎬 Jai Hind (1994) / 🎙️ S. P. Sailaja, Suresh Peters / 🎼 Vidyasagar / 📝 Vairamuthu" },
{ file: "Kanna En Selaikulla.mp3", details: "🎬 Jai Hind (1994) / 🎙️ S. P. Balasubrahmanyam, S. Janaki / 🎼 Vidyasagar / 📝 Vairamuthu" },
{ file: "Mutham thara.mp3", details: "🎬 Jai Hind (1994) / 🎙️ Mano, Sindhu / 🎼 Vidyasagar / 📝 Vairamuthu" },
{ file: "Thanni Vachu.mp3", details: "🎬 Jai Hind (1994) / 🎙️ Arjun, Malgudi Shubha, Vidyasagar / 🎼 Vidyasagar / 📝 Vairamuthu" },
{ file: "Katchi Sera.mp3", details: "💿 Think Indie (2024) / 🎙️ Sai Abhyankar / 🎼 Sai Abhyankar / 📝 Adesh Krishna" },
{ file: "Ordinary Person.mp3", details: "🎬 Leo (2023) / 🎙️ Anirudh Ravichander, Nikhita Gandhi / 🎼 Anirudh Ravichander / 📝 Heisenberg" },
{ file: "Kannathil Kannam.mp3", details: "🎬 Watchman Vadivel (1994) / 🎙️ S. P. Balasubrahmanyam, K. S. Chithra / 🎼 Deva / 📝 Vaali" },
{ file: "Chandiranum Sooriyanum.mp3", details: "🎬 Watchman Vadivel (1994) / 🎙️ S. P. Balasubrahmanyam, K. S. Chithra / 🎼 Deva / 📝 Vaali" },
{ file: "tamil_iragai_pole_clup_mix_tape.mp3", details: "Remix By dj jose" },
{ file: "Kissik.mp3", details: "🎬 Pushpa 2: The Rule (2024) / 🎙️ Sreeleela / 🎼 Devi Sri Prasad / 📝 Chandrabose" },
{ file: "Pushpa Pushpa.mp3", details: "🎬 Pushpa 2: The Rule (2024) / 🎙️ Nakash Aziz / 🎼 Devi Sri Prasad / 📝 Chandrabose" },
{ file: "Kavalaiyai Theerpadhu Naatiya.mp3", details: "🎬 Sivakavi (1943) / 🎙️ M. K. Thyagaraja Bhagavathar / 🎼 Papanasam Sivan / 📝 Papanasam Sivan" },
{ file: "Soppana Vaazhvil.mp3", details: "🎬 Sivakavi (1943) / 🎙️ M. K. Thyagaraja Bhagavathar / 🎼 Papanasam Sivan / 📝 Papanasam Sivan" },
{ file: "Vadhaname Chandra Bimbamo.mp3", details: "🎬 Sivakavi (1943) / 🎙️ M. K. Thyagaraja Bhagavathar / 🎼 Papanasam Sivan / 📝 Papanasam Sivan" },
{ file: "Vallalai Paadum Vaayal.mp3", details: "🎬 Sivakavi (1943) / 🎙️ M. K. Thyagaraja Bhagavathar / 🎼 Papanasam Sivan" },
{ file: "Vasantha Ruthu.mp3", details: "🎬 Sivakavi (1943) / 🎙️ M. K. Thyagaraja Bhagavathar, S. Jayalakshmi / 🎼 Papanasam Sivan / 📝 Papanasam Sivan" },
{ file: "Aagaya Vennilavae.mp3", details: "🎬 Arangetra Velai (1990) / 🎙️ K. J. Yesudas, Uma Ramanan / 🎼 Ilaiyaraaja / 📝 Vaali" },
{ file: "Pattu Poove.mp3", details: "🎬 Sembaruthi (1992) / 🎙️ S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali" },
{ file: "Nila Kayum Neram.mp3", details: "🎬 Sembaruthi (1992) / 🎙️ Mano, S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali" },
{ file: "Nadanthaal.mp3", details: "🎬 Sembaruthi (1992) / 🎙️ S. P. Balasubrahmanyam / 🎼 Ilaiyaraaja / 📝 Vaali" },
{ file: "Kadalile Thanimayil.mp3", details: "🎬 Sembaruthi (1992) / 🎙️ Nagoor Haniffa, Mano / 🎼 Ilaiyaraaja / 📝 Vaali" },
{ file: "Kadalile Ezhumpura.mp3", details: "🎬 Sembaruthi (1992) / 🎙️ Ilaiyaraaja / 🎼 Ilaiyaraaja / 📝 Vaali" },
{ file: "Chemparuthi Poovu.mp3", details: "🎬 Sembaruthi (1992) / 🎙️ Mano, K. S. Chithra, Dr. Bhanumathi / 🎼 Ilaiyaraaja / 📝 Vaali" },
{ file: "Chalakku Chalakku Selai.mp3", details: "🎬 Sembaruthi (1992) / 🎙️ Mano, S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali" },
{ file: "Boom shakala.mp3", details: "🎬 Kulir 100 Degrees (2015) / 🎙️ Bobo Shashi, Benny Dayal, Abishek & Nrithya / 🎼 Bobo Shashi / 📝 Pa. Vijay" },
{ file: "Ayyayo Nenju.mp3", details: "🎬 Aadukalam (2011) / 🎙️ G. V. Prakash Kumar, S. P. Balasubrahmanyam, S. P. B. Charan, Prashanthini / 🎼 G. V. Prakash Kumar / 📝 Snehan" },
{ file: "Otha Sollaala.mp3", details: "🎬 Aadukalam (2011) / 🎙️ G. V. Prakash Kumar, Velmurugan / 🎼 G. V. Prakash Kumar / 📝 Snehan" },
{ file: "Yathe Yathe.mp3", details: "🎬 Aadukalam (2011) / 🎙️ G. V. Prakash Kumar / 🎼 G. V. Prakash Kumar / 📝 Snehan" },
{ file: "Ponnu Oruthi Summa.mp3", details: "🎬 Charlie Chaplin (2002) / 🎙️ S. P. Balasubrahmanyam, Harish Ragavendra / 🎼 Bharani / 📝 Palani Bharathi" },
{ file: "Ava Kanna Partha.mp3", details: "🎬 Charlie Chaplin (2002) / 🎙️ S. P. Balasubrahmanyam, Harish Ragavendra / 🎼 Bharani / 📝 Palani Bharathi" },
{ file: "Muthalam Santhipil.mp3", details: "🎬 Charlie Chaplin (2002) / 🎙️ Swarnalatha, Unni Krishnan / 🎼 Bharani / 📝 Palani Bharathi" },
{ file: "Unthan Vizhi Munai.mp3", details: "🎬 4 Students (2004) / 🎙️ Jassie Gift, Jyotsna / 🎼 Jassie Gift / 📝 Palani Bharathi" },
{ file: "Lajjavathiyea.mp3", details: "🎬 4 Students (2004) / 🎙️ Jassie Gift / 🎼 Jassie Gift / 📝 Palani Bharathi" },
{ file: "Lajjavathiyea II.mp3", details: "🎬 4 Students (2004) / 🎙️ Jassie Gift / 🎼 Jassie Gift / 📝 Palani Bharathi" },
{ file: "Annakili II.mp3", details: "🎬 4 Students (2004) / 🎙️ Prasanna chorus / 🎼 Jassie Gift / 📝 Palani Bharathi" },
{ file: "Annakili.mp3", details: "🎬 4 Students (2004) / 🎙️ Jassie Gift / 🎼 Jassie Gift / 📝 Kaithapram" },
{ file: "Padagottum Pattamma.mp3", details: "🎬 Chinnavar (2020) / 🎙️ Malaysia Vasudevan, K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Gangai Amaran" },
{ file: "Maaraappu Chela.mp3", details: "🎬 Chinnavar (2020) / 🎙️ Mano, K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Gangai Amaran" },
{ file: "Kottukkili.mp3", details: "🎬 Chinnavar (2020) / 🎙️ K. S. Chithra, S. P. Balasubrahmanyam / 🎼 Ilaiyaraaja / 📝 Gangai Amaran" },
             { file: "Gunturu Gongura.mp3", details: "🎬 Chinnavar (2020) / 🎙️ Mano, K. S. Chithra / 🎼 Ilaiyaraaja / 📝 Gangai Amaran" },
         { file: "Paal Vannam.mp3", details: "🎬 Paasam (1962) / 🎤 P. B. Srinivas, P. Susheela / 🎼 Viswanathan - Ramamoorthy" },
             { file: "Andhiyiley Vaanam.mp3", details: "🎬 Chinnavar (2020) / 🎙️ Mano, Swarnalatha / 🎼 Ilayaraja / 📝 Gangai Amaran" },
             { file: "Kadavullum Neeyam.mp3", details: "🎬 Sindhu Nathi Poo (1994) / 🎙️ Unni Menon, S. Janaki / 🎼 Soundaryan / 📝 Vairamuthu" },
             { file: "Adiye Adi Chinnapulla.mp3", details: "🎬 Sindhu Nathi Poo (1994) / 🎙️ Mano, S. Janaki / 🎼 Soundaryan / 📝 Vairamuthu" },
             { file: "Mathalam Kottudhadi.mp3", details: "🎬 Sindhu Nathi Poo (1994) / 🎙️ S. P. Balasubrahmanyam, Swarnalatha, Loose Mohan / 🎼 Soundaryan / 📝 Vairamuthu" },
             { file: "Aathadi Enna Odambu.mp3", details: "🎬 Sindhu Nathi Poo (1994) / 🎙️ Shahul Hameed / 🎼 Soundaryan / 📝 Vairamuthu" },
             { file: "Aathi Vadayile.mp3", details: "🎬 Sindhu Nathi Poo (1994) / 🎙️ K. J. Yesudas / 🎼 Soundaryan / 📝 Vairamuthu" },
             { file: "Poi Vaada.mp3", details: "🎬 Dharmadurai (2016) / 🎙️ Srimathumitha / 🎼 Yuvan Shankar Raja / 📝 Vairamuthu" },
             { file: "Endha Pakkam.mp3", details: "🎬 Dharmadurai (2016) / 🎙️ Rahul Nambiar, Chinmayi Sripada / 🎼 Yuvan Shankar Raja / 📝 Vairamuthu" },
             { file: "Makka Kalanguthappa.mp3", details: "🎬 Dharmadurai (2016) / 🎙️ Mathichiyam Bala / 🎼 Yuvan Shankar Raja / 📝 Mathichiyam Bala" },
             { file: "Aandipatti.mp3", details: "🎬 Dharmadurai (2016) / 🎙️ Senthil Dass, Surmukhi / 🎼 Yuvan Shankar Raja / 📝 Vairamuthu" },
             { file: "Adi Raakkumuthu.mp3", details: "🎬 Ejamaan (1993) / 🎙️ S.P. Balasubrahmanyam / 🎼 Ilaiyaraaja / 📝 Vaali" },
     { file: "Ulagam Piranthathu.mp3", details: "🎬 Paasam (1962) / 🎤 T. M. Soundararajan / 🎼 Viswanathan - Ramamoorthy / 📝 Kannadasan" },
             { file: "Nilave Mugam.mp3", details: "🎬 Ejamaan (1993) / 🎙️ S. P. Balasubrahmanyam, S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali" },
             { file: "Oru Naalum Unai.mp3", details: "🎬 Ejamaan (1993) / 🎙️ S. P. Balasubrahmanyam, S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali" },
             { file: "Urakka Kaththu.mp3", details: "🎬 Ejamaan (1993) / 🎙️ S. Janaki / 🎼 Ilaiyaraaja / 📝 Vaali" },
 { file: "Poothathu_Poonthoppu.mp3", details: "🎬 Thanga Manasukkaran / 1992 /🎙️  Mano, S.Janaki /🎼  Ilaiyaraaja / 📝 Piraisoodan, Kamakodiyan, GangaiAmaran" },
             { file: "Aalappol_Velapol.mp3", details: "🎬 Ejamaan (1993) / 🎤 S.P. Balasubrahmanyam, Chithra / 🎼 Ilaiyaraaja / 📝 Vaali" },
   { file: "Peelings.mp3", details: "🎬 Pushpa 2 - The Rule ( Tamil) / 2024 /🎙️ Senthil Ganesh, Rajalakshmi /🎼 Devi Sri Prasad / 📝 Viveka, Siju Thuravoor" },
     { file: "Nee_Pottu_Vacha.mp3", details: "🎬 Ponmana Selvan (1989) / 🎤 Malaysia Vasudevan, Mano, K.S. Chithra / 🎼 Ilaiyaraaja / 📝 Gangai Amaran" },
      { file: "Naa_Ready.mp3", details: "🎬 Leo (2023) / 🎤 Thalapathy Vijay, Anirudh Ravichander / 🎼 Anirudh Ravichander / 📝 Vishnu Edavan" },
     { file: "Hey_Minnale.mp3", details: "🎬 Amaran (2024) / 🎤 Haricharan, Shweta Mohan / 🎼 G.V Prakash Kumar / 📝 Karthik Netha" },
     { file: "Achacho.mp3", details: "🎬 Aranmanai 4 (2024) / 🎤 Kharesma Ravichandran, Srinisha Jayaseelan, Hiphop Tamizha / 🎼 Hiphop Tamizha / 📝 Vignesh Srikanth" },
     { file: "Edho Solla.mp3", details: "🎬 Murungakkai Chips (2020) / 🎤 Sid Sriram / 🎼 Dharan Kumar / 📝 Ravindhar Chandrasekaran" },
      { file: "Chillanjirukkiye.mp3", details: "🎬 Lubber Pandhu (2024) / 🎤 Pradeep Kumar, Shivangi / 🎼 Sean Roldan / 📝 Mohan Rajan" }
    ]
  },

  {
    url: "https://github.com/atsuperman/PLAY/raw/main/",
    songs: [
     { file: "Beer_song_Pacha_Kuthikennen.mp3", details: "🎬 Diesel (2024) / 🎤 Gana Guna, Dhibu Ninan Thomas, Maniratnam, Kapil Kapilan / 🎼 Dhibu Ninan Thomas / 📝 Rokesh" },
     { file: "Kaattumalli.mp3", details: "🎬 Viduthalai Part 1 (2023) / 🎤 Ilaiyaraaja, Ananya Bhat / 🎼 Ilaiyaraaja / 📝 Ilaiyaraaja" }
    ]
  }
];

// Generate allSongs with encoded URLs
export const allSongs = repositories.flatMap(repo => 
  repo.songs.map(song => ({
    ...song,
    path: `${repo.url}${song.file}`.replace(/ /g, '%20') // Encode spaces
  }))
);
